services:
  modpack-init:
    build: ./init
    volumes:
      - ./modpacks:/modpacks
    environment:
      - MODPACK_URL=https://edge.forgecdn.net/files/6658/547/Create-Ultimate%20Selection%20Serverpack%20MC%201.20.1-12.6.0.zip
    command: ["sh", "/init/download.sh"]
    restart: "no"
  modpack-runner:
    build: ./minecraft
    environment:
      MODPACK_ZIP: modpack.zip  # <- Change this if needed
      RCON_PASSWORD: password
      CONTROL_PORT: 8080
    volumes:
      - ./modpacks:/downloads         # Mount the local downloads folder
      - ./overrides:/overrides
      - ./data:/opt/app
    ports:
      - 25565:25565
      - 24454:24454
      - 8080:8080
  backup-service:
    build: ./backup  # Directory where Dockerfile, backup.sh, entrypoint.sh are located
    environment:
      WORLD_ID: gooners
      BACKUP_INTERVAL_H: 2
      DEBUG_CRON: 0
      GIT_REPO: git@github.com:CodingJinxx/EnderNetBackups.git
      RCON_HOST: modpack-runner
      RCON_PASSWORD: password
      RCON_PORT: 25575
      CONTROL_HOST: modpack-runner
      CONTROL_PORT: 8080
    volumes:
      - ./data:/data                    # Minecraft world directory
      - ./world_backups:/backups                # Where zipped backups are staged
      - ./ssh:/ssh                      # SSH private key for Git access
      - ./replaced_worlds:/replaced_worlds  # Optional: store replaced worlds
    depends_on:
      - modpack-runner
    restart: no
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    network_mode: bridge
    ports:
      - 8000:8000/tcp
    volumes:
      - ./ddns:/updater/data
    environment:
      - CONFIG=
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=all
      - PUBLICIPV4_HTTP_PROVIDERS=all
      - PUBLICIPV6_HTTP_PROVIDERS=all
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=3s
      - HTTP_TIMEOUT=10s

      # Web UI
      - LISTENING_ADDRESS=:8000
      - ROOT_URL=/

      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/updater/data

      # Other
      - LOG_LEVEL=info
      - LOG_CALLER=hidden
      - SHOUTRRR_ADDRESSES=
    restart: always
